version: "3.9"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000                # Replace with your user ID
      - PGID=1000                # Replace with your group ID
      - VERSION=docker
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - /home/manupa/Downloads:/data
    restart: unless-stopped
